version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: agendamento-mysql
    restart: always
    environment:
      MYSQL_DATABASE: agendamento
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
